### ISSUE TITLE
程序运行报错（测试了kali自带的原版sqlmap执行同样的命令无报错）

### ISSUE THREAD

**Issue by zcbxxx1** [BugFor-Pings/CN_Sqlmap#2]
![图片](https://github.com/BugFor-Pings/CN_Sqlmap/assets/56199489/8b68876d-cbc4-4f75-a34a-5dca670096af)
[23:20:16] [CRITICAL] sqlmap/1.7.1.1#dev 中发生未处理的异常. 建议您重试 使用官方GitHub的最新开发版本运行存储库位于 'https://github.com/sqlmapproject/sqlmap'. 如果异常仍然存在，请打开新问题 at 'https://github.com/sqlmapproject/sqlmap/issues/new' 带有以下文本和再现错误所需的任何其他信息开发人员将尝试重现该错误. 开发人员将尝试复制该错误,并相应地修复它 然后返回给您正在运行的版本: 1.7.1.1#dev
Python 版本: 3.11.4
操作系统: Linux-6.3.0-kali1-amd64-x86_64-with-glibc2.37
命令行: sqlmap.py --wizard
技巧: TIME
后端DBMS: MySQL (指纹)
Traceback (most recent call last):
  File "sqlmap.py", line 224, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/controller/controller.py", line 715, in start
    action()
  File "lib/controller/action.py", line 171, in action
    conf.dbmsHandler.dumpAll()
  File "plugins/generic/entries.py", line 513, in dumpAll
    self.dumpTable()
  File "plugins/generic/entries.py", line 466, in dumpTable
    conf.dumper.dbTableValues(kb.data.dumpedTable)
  File "lib/core/dump.py", line 518, in dbTableValues
    data_values=tableValues[columns[0]]['values']
                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'values'



[*] ending @ 23:21:30 /2023-07-26/

**Comment by BugFor-Pings** [comment]
很久没看github，现在更新了1.9版本了
